"use strict";
exports.__esModule = true;
var inmobiliaria_1 = require("./inmobiliaria");
var lote_1 = require("./lote");
var casa_1 = require("./casa");
var departamento_1 = require("./departamento");
var miListaPropiedades = [];
var miInmobiliaria = new inmobiliaria_1.Inmobiliaria(miListaPropiedades);
var vivienda1 = new departamento_1.Departamento(1500, 2, 1, false, false, "JuanGarcia", "Alem 345", 13000, "Alquiler", 45, 1990);
var vivienda2 = new casa_1.Casa(true, 3, 1, true, false, "MariaPerez", "Rodrigrez 432", 14500, "Alquiler", 60, 1772);
var vivienda3 = new casa_1.Casa(false, 2, 1, true, false, "HugoSanchez", "Alberdi 224", 15000, "Alquiler", 70, 1920);
var vivienda4 = new departamento_1.Departamento(4000, 4, 2, true, false, "JorgeMuñoz", "Mitre 344 4toA", 28000, "Alquiler", 80, 1722);
var lote1 = new lote_1.Lote(false, "PedroLopez", "Los Ombues 1000", 345000, "Venta", 300, 11182);
var lote2 = new lote_1.Lote(true, "MercedesPaz", "Calihue 2222", 300000, "Venta", 250, 18292);
var lote3 = new lote_1.Lote(false, "CelesteMendoza", "Los Tilos 110", 250000, "Venta", 200, 18299);
miInmobiliaria.ingresarPropiedad(vivienda1);
miInmobiliaria.ingresarPropiedad(vivienda2);
miInmobiliaria.ingresarPropiedad(vivienda3);
miInmobiliaria.ingresarPropiedad(vivienda4);
miInmobiliaria.ingresarPropiedad(lote1);
miInmobiliaria.ingresarPropiedad(lote2);
miInmobiliaria.ingresarPropiedad(lote3);
//miInmobiliaria.buscarPropiedad(1990);
//console.log(miListaPropiedades);
console.log(miInmobiliaria.listarAlquileres());
//console.log(miInmobiliaria.listarVentas());
miInmobiliaria.borrarPropiedad(1920);
console.log(miInmobiliaria.listarAlquileres());
console.log(miInmobiliaria.buscarPropiedad(1990).getTipoTransaccion());
console.log(miInmobiliaria.buscarPropiedad(18299).getValor());
