USE ejemplo_almacenes;
CREATE TABLE IF NOT EXISTS `DEPARTAMENTO`(
idDepto INT NOT NULL,
nombre VARCHAR(45),
PRIMARY KEY (idDepto)
);

CREATE TABLE IF NOT EXISTS `EMPLEADO`(
nroEmpleado INT NOT NULL,
nombre VARCHAR(45),
direccion VARCHAR(45),
DEPARTAMENTO_idDepto INT,
PRIMARY KEY (nroEmpleado),
CONSTRAINT empleado_dpto FOREIGN KEY (DEPARTAMENTO_idDepto) REFERENCES `DEPARTAMENTO` (idDepto)
);

CREATE TABLE IF NOT EXISTS `FABRICANTE`(
idFabricante INT NOT NULL,
nombre VARCHAR(45),
direccion VARCHAR(45),
PRIMARY KEY (idFabricante)
);

CREATE TABLE IF NOT EXISTS `PRODUCTO`(
idProducto INT NOT NULL,
idAlmacen VARCHAR(45) NOT NULL,
nombre VARCHAR(45),
precio VARCHAR(45),
DEPARTAMENTO_idDepto INT,
FABRICANTE_idFabricante INT,
PRIMARY KEY (idProducto, idAlmacen),
CONSTRAINT producto_depto FOREIGN KEY (DEPARTAMENTO_idDepto) REFERENCES DEPARTAMENTO (idDepto),
CONSTRAINT producto_fabricante FOREIGN KEY (FABRICANTE_idFabricante) REFERENCES FABRICANTE (idFabricante)
);