USE EMPRESA_AERONAUTICA;

CREATE TABLE IF NOT EXISTS `EMPRESA`(
idEmpresa INT NOT NULL,
PRIMARY KEY (idEmpresa)
);

CREATE TABLE IF NOT EXISTS `EMPLEADO`(
idEmpleado INT NOT NULL,
tipoEmpleado VARCHAR(45),
EMPRESA_idEmpresa INT,
PRIMARY KEY (idEmpleado),
CONSTRAINT empleado_empresa FOREIGN KEY (EMPRESA_idEmpresa) REFERENCES `EMPRESA`(idEmpresa)
);

CREATE TABLE IF NOT EXISTS `OPERARIO`(
idOperario INT NOT NULL,
EMPLEADO_idEmpleado INT,
PRIMARY KEY (idOperario),
CONSTRAINT operario_empleado FOREIGN KEY (EMPLEADO_idEmpleado) REFERENCES `EMPLEADO`(idEmpleado)
);

CREATE TABLE IF NOT EXISTS `AUDITOR`(
idAuditor INT NOT NULL,
EMPLEADO_idEmpleado INT,
PRIMARY KEY (idAuditor),
CONSTRAINT auditor_empleado FOREIGN KEY (EMPLEADO_idEmpleado) REFERENCES `EMPLEADO`(idEmpleado)
);

CREATE TABLE IF NOT EXISTS `GERENTE`(
idGerente INT NOT NULL,
EMPLEADO_idEmpleado INT,
PRIMARY KEY (idGerente),
CONSTRAINT gerente_empleado FOREIGN KEY (EMPLEADO_idEmpleado) REFERENCES `EMPLEADO`(idEmpleado)
);

CREATE TABLE IF NOT EXISTS `EQUIPO`(
idEquipo INT NOT NULL,
PRIMARY KEY (idEquipo)
);

CREATE TABLE IF NOT EXISTS `EQUIPO_EMPLEADO`(
EMPLEADO_idEMPLEADO INT,
EQUIPO_idEQUIPO INT,
CONSTRAINT empleado_empleado FOREIGN KEY (EMPLEADO_idEMPLEADO) REFERENCES `EMPLEADO`(idEmpleado),
CONSTRAINT equipo_equipo FOREIGN KEY (EQUIPO_idEQUIPO) REFERENCES `EQUIPO`(idEquipo)
);

CREATE TABLE IF NOT EXISTS `AVION`(
idAvion INT NOT NULL,
EQUIPO_idEQUIPO INT,
PRIMARY KEY (idAvion),
CONSTRAINT equipo_avion FOREIGN KEY (EQUIPO_idEQUIPO) REFERENCES `EQUIPO`(idEquipo)
);

CREATE TABLE IF NOT EXISTS `COMPONENTE`(
idComponente INT NOT NULL,
AVION_idAVION INT,
PRIMARY KEY (idComponente),
CONSTRAINT componente_avion FOREIGN KEY (AVION_idAVION) REFERENCES `AVION`(idAvion)
);